name: cloud_vault
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core:
  firebase_auth:
  firebase_storage:
  cloud_firestore:
  sizer: ^2.0.15
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  google_fonts: ^5.1.0
  flutter_animate: ^4.2.0
  file_picker: ^5.3.2
  
  dio: ^5.2.1+1
  url_launcher: ^6.1.12
  http: ^1.1.0
  cached_network_image:
  flutter_cache_manager: ^3.3.1
  video_player: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
